FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["bl_word_game.csproj", "."]
RUN dotnet restore "./bl_word_game.csproj"
COPY . .
WORKDIR "/src/."
RUN dotnet build "bl_word_game.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "bl_word_game.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "bl_word_game.dll"]